var annotated_dup =
[
    [ "qBitField_t", "structq_bit_field__t.html", null ],
    [ "qFIS_Input_t", "structq_f_i_s___input__t.html", null ],
    [ "qFIS_MF_t", "structq_f_i_s___m_f__t.html", null ],
    [ "qFIS_Output_t", "structq_f_i_s___output__t.html", null ],
    [ "qFIS_t", "structq_f_i_s__t.html", null ],
    [ "qFP16_Settings_t", "structq_f_p16___settings__t.html", null ],
    [ "qLTISys_t", "structq_l_t_i_sys__t.html", null ],
    [ "qNumA_state_t", "structq_num_a__state__t.html", null ],
    [ "qPID_AutoTuning_t", "structq_p_i_d___auto_tuning__t.html", null ],
    [ "qPID_controller_t", "structq_p_i_d__controller__t.html", null ],
    [ "qPID_Gains_t", "structq_p_i_d___gains__t.html", "structq_p_i_d___gains__t" ],
    [ "qRMS_t", "structq_r_m_s__t.html", null ],
    [ "qSSmoother_ALNF_t", "structq_s_smoother___a_l_n_f__t.html", null ],
    [ "qSSmoother_DESF_t", "structq_s_smoother___d_e_s_f__t.html", null ],
    [ "qSSmoother_EXPW_t", "structq_s_smoother___e_x_p_w__t.html", null ],
    [ "qSSmoother_GMWF_t", "structq_s_smoother___g_m_w_f__t.html", null ],
    [ "qSSmoother_KLMN_t", "structq_s_smoother___k_l_m_n__t.html", null ],
    [ "qSSmoother_LPF1_t", "structq_s_smoother___l_p_f1__t.html", null ],
    [ "qSSmoother_LPF2_t", "structq_s_smoother___l_p_f2__t.html", null ],
    [ "qSSmoother_MOR1_t", "structq_s_smoother___m_o_r1__t.html", null ],
    [ "qSSmoother_MOR2_t", "structq_s_smoother___m_o_r2__t.html", null ],
    [ "qSSmoother_MWM1_t", "structq_s_smoother___m_w_m1__t.html", null ],
    [ "qSSmoother_MWM2_t", "structq_s_smoother___m_w_m2__t.html", null ],
    [ "qTDL_t", "structq_t_d_l__t.html", null ],
    [ "qVFloat_MinMax_t", "structq_v_float___min_max__t.html", "structq_v_float___min_max__t" ],
    [ "qVFloat_Moment_t", "structq_v_float___moment__t.html", "structq_v_float___moment__t" ]
];