var searchData=
[
  ['end_0',['END',['../group__qfis.html#ga29fd18bed01c4d836c7ebfe73a125c3f',1,'qfis.h']]],
  ['engine_1',['Fuzzy Inference System Engine',['../qfis_desc.html',1,'index']]],
  ['equation_2',['Example: Solution of the quadratic equation',['../qfp16_desc.html#qfp16_example',1,'']]],
  ['estimator_3',['Recursive Root Mean Square estimator',['../qrms_desc.html',1,'index']]],
  ['evaluate_20the_20given_20continuous_20transfer_20function_4',['Example: Evaluate the given continuous transfer function',['../qltisys_desc.html#qltisys_ex1',1,'']]],
  ['evaluate_20the_20given_20discrete_20transfer_20function_5',['Example: Evaluate the given discrete transfer function',['../qltisys_desc.html#qltisys_ex2',1,'']]],
  ['evaluating_20a_20fuzzy_20inference_20system_6',['Evaluating a Fuzzy Inference System',['../qfis_desc.html#qfis_eval',1,'']]],
  ['evaluation_20by_20transfer_20functions_7',['Recursive LTI Systems Evaluation by transfer functions.',['../qltisys_desc.html',1,'index']]],
  ['example_20_3a_20by_20using_20a_20timer_20interrupt_8',['Example :  By using a timer interrupt',['../qrms_desc.html#qrms_ex1',1,'']]],
  ['example_20_3a_20code_20snippet_20that_20demonstrates_20the_20spline_20interpolation_9',['Example : Code snippet that demonstrates the spline interpolation .',['../qinterp1_desc.html#qinterp1_ex1',1,'']]],
  ['example_20_3a_20code_20snippet_20to_20instantiate_20a_20tdl_20to_20hold_20up_20to_20256_20delays_10',['Example : Code snippet to instantiate a TDL to hold up to 256 delays.',['../qtdl_desc.html#qtdl_ex1',1,'']]],
  ['example_20of_20signal_20smoothing_11',['Example of signal smoothing',['../qssmoother_desc.html#qssmoother_ex10',1,'']]],
  ['example_3a_20evaluate_20the_20given_20continuous_20transfer_20function_12',['Example: Evaluate the given continuous transfer function',['../qltisys_desc.html#qltisys_ex1',1,'']]],
  ['example_3a_20evaluate_20the_20given_20discrete_20transfer_20function_13',['Example: Evaluate the given discrete transfer function',['../qltisys_desc.html#qltisys_ex2',1,'']]],
  ['example_3a_20setting_20up_20a_201st_20order_20low_20pass_20filter_3a_14',['Example: setting up a 1st order low-pass filter:',['../qssmoother_desc.html#qssmoother_ex1',1,'']]],
  ['example_3a_20setting_20up_20a_202nd_20order_20low_20pass_20filter_3a_15',['Example: setting up a 2nd order low-pass filter:',['../qssmoother_desc.html#qssmoother_ex2',1,'']]],
  ['example_3a_20setting_20up_20a_20gaussian_20filter_3a_16',['Example: setting up a gaussian filter:',['../qssmoother_desc.html#qssmoother_ex7',1,'']]],
  ['example_3a_20setting_20up_20a_20moving_20window_20median_20filter_3a_17',['Example: Setting up a moving window median filter:',['../qssmoother_desc.html#qssmoother_ex4',1,'']]],
  ['example_3a_20setting_20up_20a_20moving_20window_20median_20filter_3a_18',['Example: setting up a moving window median filter:',['../qssmoother_desc.html#qssmoother_ex3',1,'']]],
  ['example_3a_20setting_20up_20a_20scalar_20kalman_20filter_3a_19',['Example: setting up a scalar Kalman filter:',['../qssmoother_desc.html#qssmoother_ex9',1,'']]],
  ['example_3a_20setting_20up_20an_20exponential_20weighting_20filter_3a_20',['Example: setting up an exponential weighting filter:',['../qssmoother_desc.html#qssmoother_ex8',1,'']]],
  ['example_3a_20setting_20up_20an_20outlier_20removal_20filter_3a_21',['Example: setting up an outlier removal filter:',['../qssmoother_desc.html#qssmoother_ex5',1,'Example: setting up an outlier removal filter:'],['../qssmoother_desc.html#qssmoother_ex6',1,'Example: setting up an outlier removal filter:']]],
  ['example_3a_20solution_20of_20the_20quadratic_20equation_22',['Example: Solution of the quadratic equation',['../qfp16_desc.html#qfp16_example',1,'']]],
  ['example_3a_20speed_20control_20using_20a_20pid_20controller_3a_23',['Example: Speed control using a PID controller:',['../qpid_desc.html#qpid_ex1',1,'']]],
  ['example_3a_20speed_20control_20with_20pid_20controller_20and_20autotuning_3a_24',['Example: Speed control with PID controller and autotuning:',['../qpid_desc.html#qpid_ex3',1,'']]],
  ['example_3a_20speed_20control_20with_20pid_20controller_20with_20an_20additive_20mrac_3a_25',['Example: Speed control with PID controller with an additive MRAC:',['../qpid_desc.html#qpid_ex2',1,'']]],
  ['exponential_20and_20transcendental_20functions_26',['Exponential and transcendental functions',['../qfp16_desc.html#qfp16_exp_functions',1,'']]],
  ['exponential_20smoothing_27',['Double Exponential Smoothing',['../qssmoother_desc.html#qssmoother_desf',1,'']]],
  ['exponential_20weighting_20filter_28',['Exponential Weighting filter',['../qssmoother_desc.html#qssmoother_expw',1,'']]],
  ['exponential_20weighting_20filter_3a_29',['Example: setting up an exponential weighting filter:',['../qssmoother_desc.html#qssmoother_ex8',1,'']]]
];
